---
title: Siteleaf Tester site
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: craigbrett17@aol.com
description: 'This is literally just a test site. Google will probably never see this

'
baseurl: ''
url: http://craigbrett17/siteleaf-test.github.io
twitter_username: nalagaric
github_username: craigbrett17
markdown: kramdown
